name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: rizwan/echo-site:latest

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_dir: ci/helm
          charts_repo_url: https://alifstudios.github.io/echo-site

      # - name: 'Deploy'
      #   uses: 'lab42/Helm@v21.6.1-916e8c0'
      #   with:
      #     helm: 'upgrade xvestr xvestr --install --atomic --wait --repo https://alifstudios.github.io/echo-site'
      #     repository: 'xvestr-repo https://alifstudios.github.io/echo-site'
      #     kubeconfig: '${{ secrets.KUBECONFIG }}'